Rd 817 manila sdk
cloudify-cosmo/cloudify-openstack-plugin pull request #383
Opened 2020-12-24 10:13 UTC by EarthmanT

2020-12-24 13:26 UTC, AdarShaked requested changes
+update changelog.

2020-12-24 13:34 UTC, EarthmanT commented on openstack_plugin/resources/share/network_share.py
> +        raise OperationRetry('Network share {0} is still deleting.'.format(
`openstack_resource.resource` will be `None` because `.get` will return `None`

2020-12-24 13:34 UTC, EarthmanT commented on openstack_plugin/resources/share/file_share.py
> +    openstack_resource.allow(kwargs['access'])
will fix

2020-12-24 13:34 UTC, EarthmanT commented on openstack_plugin/resources/share/file_share.py
> +        ctx.logger.info('Shared resource {0} is deleted successfully'.format(
in this plugin people have used indices I think?

2020-12-24 13:34 UTC, EarthmanT commented on openstack_plugin/resources/share/file_share.py
> +        raise NonRecoverableError('Failed to delete the resource {0}.'.format(
in this plugin people have used indices I think?

2020-12-24 19:52 UTC, AdarShaked submitted a review, later dismissed

2020-12-27 08:20 UTC, AdarShaked approved these changes

2020-12-27 08:22 UTC, merged